# Generated by Django 5.2.6 on 2025-09-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('recruiter', 'Recruiter'), ('admin', 'Admin')], db_index=True, max_length=10),
        ),
    ]
