# Generated by Django 5.2.6 on 2025-09-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
