# Generated by Django 5.2.6 on 2025-09-12 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0003_job_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='employment_types',
            new_name='employment_type',
        ),
    ]
