# Generated by Django 5.2.6 on 2025-09-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0006_application_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
