# Generated by Django 5.2.6 on 2025-09-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0008_companyreview_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('user', 'job')},
        ),
        migrations.AlterUniqueTogether(
            name='companyreview',
            unique_together={('company', 'user')},
        ),
    ]
