# Generated by Django 5.2.6 on 2025-09-18 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0009_alter_application_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyreview',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('review', 'Review')], db_index=True, default='review', max_length=20)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='job_board.companyreview')),
            ],
        ),
    ]
