# Generated by Django 5.2.6 on 2026-02-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0014_message_edited_messagehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='company',
        ),
    ]
