# Generated by Django 5.2.6 on 2026-02-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0016_message_parent_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
